name: Rust

on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    env:
      RUST_IOT_ENVIRONMENT: PRODUCTION
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_DB_NAME: ${{ secrets.SQL_DB_NAME }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
